# Generated by Django 2.2 on 2021-08-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210818_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quen',
            new_name='quan',
        ),
    ]
